/*CONSULTAS*/
/*Realizado por Julián González Dos Reis (bk0136)*/


/*INSERT INTO Usuarios (Id_U, usuario, clave, Nombre, Apellidos, correo, Num_fotos, Estado, Codigo_ColecDef, PermisoCrear,  PermisoVerPu,TipoUsuario, Validado)
VALUES (8,'paulis','0123','Paula', 'Coca Martin', 'paulis@', 10, 1, '', 1, 1, 'AD',0);
 
INSERT INTO Usuarios (Id_U, usuario, clave, Nombre, Apellidos, correo, Num_fotos, Estado, Codigo_ColecDef, PermisoCrear,  PermisoVerPu,TipoUsuario, Validado)
VALUES (9,'yulius','1234','Julian', 'Gonzalez Dos Reis', 'julipanchi@', 7, 1, '', 1, 1, 'AD',0);*/
 
/*pregunta1*/
SELECT TEMAE,ID_U,USUARIO,NOMBRE, APELLIDOS
FROM USUARIOS, ESCRIBEEMAIL
WHERE USUARIOS.id_u=ESCRIBEEMAIL.destino AND ID_U='4';
 
 
/*pregunta2*/
SELECT P.CODIGO_G AS JP_CODIGO_G , G.IDENTIFICADOR, G.ID_U, U.NOMBRE
FROM PERTENECEN P, GRUPOS G, USUARIOS U
WHERE P.ID_U='3'
AND G.CODIGO_G= p.codigo_g
AND G.ID_U= u.id_u;
 
/*pregunta 3*/
SELECT C.ID_U AS JP_ID_U, U.USUARIO, U.NOMBRE, U.APELLIDOS, E.DENOMINACION, E.PREMIOF
FROM COLECCIONES C, USUARIOS U, PRESENTAFO P, FOTOGRAFIAS F, EXPOSICIONES E
WHERE C.CODIGO_C=F.CODIGO_C
AND P.ID_F=F.ID_F
AND C.ID_U=U.ID_U
AND P.ID_E=E.ID_E
ORDER BY C.ID_U;
 
/*Pregunta 4*/
SELECT U.ID_U AS JP_ID_U, U.USUARIO
FROM USUARIOS U, PUEDEVERCOL P, COLECCIONES C
WHERE U.ID_U=C.ID_U
AND P.ID_U=U.ID_U;
 
/*Pregunta 5*/
SELECT U.ID_U AS JP_ID_U, U.USUARIO, U.NUM_FOTOS
FROM USUARIOS U
WHERE U.ESTADO='1'
AND U.NUM_FOTOS > 5;
 
/*Pregunta 6*/
SELECT U.ID_U AS JP_ID_U, U.USUARIO, C.CODIGO_C, C.DESCRIPCION
FROM USUARIOS U, COLECCIONES C, FOTOGRAFIAS F
WHERE U.ESTADO='1'
AND U.ID_U=C.ID_U
AND C.CODIGO_C=F.CODIGO_C
GROUP BY U.ID_U, U.USUARIO, c.codigo_c, C.descripcion;
 
/*Pregunta 7*/
SELECT U1.ID_U AS JP_ID_U, U1.USUARIO, U1.NOMBRE, E.REMITENTE AS U_REMITENTE, U2.USUARIO AS U_REMITENTE, U2.NOMBRE, E.FECHA
FROM USUARIOS U1, ESCRIBEEMAIL E, USUARIOS U2
WHERE E.FECHA<'01/01/2017'
AND U1.ID_U=E.DESTINO
AND E.TEMAE='Revocar'
AND U2.ID_U=E.REMITENTE;
 
/*Pregunta 8*/
SELECT G.CODIGO_G AS JP_CODIGO_G, G.IDENTIFICADOR, U.ID_U, U.NOMBRE, U.APELLIDOS
FROM USUARIOS U, GRUPOS G, FOTOGRAFIAS F, GRUPOVEFOTO GV, COLECCIONES C
WHERE C.ID_U='1'
AND C.CODIGO_C=F.CODIGO_C
AND F.ID_F=GV.ID_F
AND GV.CODIGO_G=G.CODIGO_G
AND G.ID_U=U.ID_U
UNION
SELECT G.CODIGO_G AS JP_CODIGO_G, G.IDENTIFICADOR, U.ID_U,U.NOMBRE, U.APELLIDOS
FROM USUARIOS U, GRUPOS G, FOTOGRAFIAS F, GRUPOVECOL GV, COLECCIONES C
WHERE C.ID_U='1'
AND C.CODIGO_C=F.CODIGO_C
AND GV.CODIGO_G=G.CODIGO_G
AND G.ID_U=U.ID_U;
 
/*Pregunta 9*/
SELECT DISTINCT U.USUARIO AS PREGUNTAO9JP_USUARIO, U.NOMBRE, U.APELLIDOS
FROM PRESENTAFO PF, FOTOGRAFIAS F, COLECCIONES C, USUARIOS U
WHERE F.ID_F = PF.ID_F
AND C.CODIGO_C NOT IN (SELECT CODIGO_C FROM FOTOGRAFIAS);
/*SELECT U.USUARIO AS JP_USUARIO, U.NOMBRE, U.APELLIDOS,E.DENOMINACION, E.PREMIOF
FROM USUARIOS U, EXPOSICIONES E, PRESENTAFO PF, FOTOGRAFIAS F, COLECCIONES C
WHERE PF.ID_F=F.ID_F
AND PF.ID_E=E.ID_E
AND F.CODIGO_C=C.CODIGO_C
AND C.ID_U=U.ID_U;
/*NOT IN(
SELECT U.USUARIO AS JP_USUARIO, U.NOMBRE, U.APELLIDOS,E.DENOMINACION, E.PREMIOF
FROM USUARIOS U, EXPOSICIONES E, PRESENTACO PC, FOTOGRAFIAS F, COLECCIONES C
WHERE PC.CODIGO_C=F.CODIGO_C
AND F.CODIGO_C= C.CODIGO_C
AND C.ID_U=U.ID_U
AND PC.ID_E=E.ID_E);/*
 
/*Pregunta 10*/
SELECT DISTINCT U.USUARIO AS PREGUNTA10JP_USUARIO, U.NOMBRE
FROM USUARIOS U, PUEDEVERCOL PC
WHERE PC.ID_U=U.ID_U
AND((SELECT COUNT (PF.ID_U) FROM PUEDEVERFOTO PF)>2);
 
/*Pregunta 11*/
SELECT DISTINCT U.ID_U AS PREGUNTA11JP_ID_U, U.USUARIO, U.NOMBRE, U.APELLIDOS, COUNT(DP.userdapermiso) AS TOTALPERMISOS
FROM USUARIOS U, DAPERMISOS DP
WHERE DP.PERMISO='PermisoCrear'
AND DP.USERDAPERMISO=U.ID_U
GROUP BY U.ID_U, U.USUARIO, U.NOMBRE, U.APELLIDOS;

/*Pregunta 12*/
SELECT U.ID_U AS JP_ID_U, U.USUARIO, U.NOMBRE, U.APELLIDOS, DP.FECHA
FROM USUARIOS U, DAPERMISOS DP
WHERE DP.USERRECIBEPERM=U.ID_U
AND DP.PERMISO='VerPublic';
 
/*Pregunta 13*/
SELECT U.ID_U AS JP_ID_U, U.USUARIO, U.NOMBRE, U.APELLIDOS
FROM USUARIOS U;
 
/*Pregunta 14*/
SELECT DISTINCT C.CODIGO_C AS JP_CODIGO_C, C.DESCRIPCION
FROM COLECCIONES C, EXPOSICIONES E, PRESENTACO PC
WHERE C.CODIGO_C=PC.CODIGO_C
AND PC.ID_E=E.ID_E
AND EXISTS(SELECT C.CODIGO_C FROM COLECCIONES C WHERE EXISTS(SELECT * FROM PRESENTACO PC WHERE PC.CODIGO_C=C.CODIGO_C));
 
/*Pregunta 15*/
SELECT DISTINCT U.ID_U AS JP_ID_U, U.USUARIO
FROM USUARIOS U, SOLICITAENTRADAS SE, FOTOGRAFIAS F, PRESENTAFO PF, COLECCIONES C
WHERE SE.ID_U=U.ID_U
AND PF.ID_F=F.ID_F
AND F.CODIGO_C=C.CODIGO_C
AND C.ID_U=SE.ID_U;
 
/*Pregunta 16*/
/*SELECT DISTINCT U.ID_U AS JP_ID_U, U.USUARIO
FROM USUARIOS U, PUEDEVERCOL PC
WHERE U.ID_U=PC.ID_U;*/
/*FALTA CODIGO*/
SELECT COUNT(*) AS P16JP_COUNT, U.USUARIO, U.NOMBRE, U.APELLIDOS
FROM USUARIOS U, DAPERMISOS DP
WHERE U.ID_U=DP.USERRECIBEPERM
AND DP.PERMISO='VerPublic'
AND DP.TIPO='Otorga'
GROUP BY U.USUARIO, U.NOMBRE, U.APELLIDOS;

/*Pregunta 17*/
SELECT SUM (E.PREMIOF+E.PREMIOC) AS JP_PREMIO
FROM EXPOSICIONES E
WHERE E.FFIN <'01/01/2018';
 
/*Pregunta 18*/
SELECT G.CODIGO_G AS JP_CODIGO_G, G.IDENTIFICADOR, COUNT(GF.CODIGO_G+GC.CODIGO_G) AS NUMERO_PERMISOS
FROM GRUPOS G, GRUPOVEFOTO GF, GRUPOVECOL GC
WHERE G.CODIGO_G=GF.CODIGO_G
AND GF.CODIGO_G=GC.CODIGO_G
GROUP BY G.CODIGO_G, G.IDENTIFICADOR;
/*Hay que hacerla con join*/
 
/*Pregunta 19*/
SELECT U.ID_U AS JP_ID_U, U.USUARIO
FROM USUARIOS U, SOLICITAENTRADAS S
WHERE U.ID_U=S.ID_U;
 
/*Pregunta 20 */
/*SELECT U.ID_U AS JP_ID_U, U.USUARIO
FROM USUARIOS U, SOLICITAENTRADAS S, PRESENTACO PC, COLECCIONES C
WHERE U.ID_U = C.ID_U
AND C.ID_U= S.ID_U
AND S.ID_E=PC.ID_E
AND PC.CODIGO_C= C.CODIGO_C
INTERSECT
SELECT U.ID_U AS JP_ID_U, U.USUARIO
FROM USUARIOS U, SOLICITAENTRADAS S, PRESENTAFOTO PF, COLECCIONES C
WHERE U.ID_U = C.ID_U
AND C.ID_U= S.ID_U
AND S.ID_E=PC.ID_E
AND PC.CODIGO_C= C.CODIGO_C;*/